package com.example.model

data class NodeXX(
    val __typename: String?,
    val accessibility_caption: String?,
    val clips_music_attribution_info: Any?,
    val comments_disabled: Boolean?,
    val dash_info: DashInfoX?,
    val dimensions: DimensionsX?,
    val display_url: String?,
    val edge_liked_by: EdgeLikedByX?,
    val edge_media_preview_like: EdgeMediaPreviewLikeX?,
    val edge_media_to_caption: EdgeMediaToCaptionX?,
    val edge_media_to_comment: EdgeMediaToCommentX?,
    val edge_media_to_tagged_user: EdgeMediaToTaggedUserX?,
    val edge_sidecar_to_children: EdgeSidecarToChildren?,
    val fact_check_information: Any?,
    val fact_check_overall_rating: Any?,
    val felix_profile_grid_crop: Any?,
    val gating_info: Any?,
    val has_audio: Boolean?,
    val id: String?,
    val is_video: Boolean?,
    val location: Location?,
    val media_overlay_info: Any?,
    val media_preview: Any?,
    val owner: OwnerXX?,
    val product_type: String?,
    val sharing_friction_info: SharingFrictionInfoXX?,
    val shortcode: String?,
    val taken_at_timestamp: Int?,
    val thumbnail_resources: List<ThumbnailResourceX>?,
    val thumbnail_src: String?,
    val tracking_token: String?,
    val video_url: String?,
    val video_view_count: Int?
)